# Generated by Django 4.1.7 on 2023-05-03 03:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_prevista', models.DateTimeField(default=datetime.datetime.now)),
                ('fecha_fin_prevista', models.DateTimeField(default=datetime.datetime(2023, 5, 16, 23, 39, 35, 617896))),
                ('fecha_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_real', models.DateTimeField(blank=True, null=True)),
                ('sprint_backlog_id', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.proyecto')),
            ],
        ),
    ]
