# Generated by Django 4.2 on 2023-04-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(choices=[('SM', 'Scrum Master'), ('PO', 'Product Owner'), ('TM', 'Team Member')], max_length=2),
        ),
    ]
