# Generated by Django 4.1.7 on 2023-05-03 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_sprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='id',
        ),
        migrations.AlterField(
            model_name='sprint',
            name='fecha_fin_prevista',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 17, 16, 51, 292287)),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='sprint_backlog_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
