# Generated by Django 4.1.7 on 2023-05-07 21:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_sprint_id_alter_sprint_fecha_fin_prevista_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('to do', 'To Do'), ('doing', 'Doing'), ('done', 'Done'), ('cancelled', 'Cancelled')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='sprint',
            name='fecha_fin_prevista',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 17, 50, 27, 474783)),
        ),
        migrations.CreateModel(
            name='UserStories',
            fields=[
                ('id_user_story', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('hecho', models.TextField()),
                ('story_points', models.IntegerField()),
                ('prioridad', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.estado')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.sprint')),
                ('usuario_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usuarioproyecto')),
            ],
        ),
    ]
