# Generated by Django 4.1.7 on 2023-05-07 22:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_estado_alter_sprint_fecha_fin_prevista_userstories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='fecha_fin_prevista',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 18, 30, 8, 339180)),
        ),
        migrations.AlterField(
            model_name='userstories',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userstories',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.estado'),
        ),
        migrations.AlterField(
            model_name='userstories',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userstories',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userstories',
            name='hecho',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userstories',
            name='prioridad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userstories',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.sprint'),
        ),
        migrations.AlterField(
            model_name='userstories',
            name='story_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userstories',
            name='usuario_proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.usuarioproyecto'),
        ),
    ]
