# Generated by Django 4.1.7 on 2023-05-12 21:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_sprint_fecha_fin_prevista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='fecha_fin_prevista',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 26, 17, 52, 4, 830076)),
        ),
        migrations.AlterField(
            model_name='userstories',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.estado'),
        ),
        migrations.AlterField(
            model_name='userstories',
            name='usuario_proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.usuarioproyecto'),
        ),
    ]
