# Generated by Django 4.1.7 on 2023-05-14 22:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_sprint_fecha_fin_prevista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='fecha_fin_prevista',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 28, 18, 52, 43, 788522)),
        ),
        migrations.AlterField(
            model_name='userstories',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.sprint'),
        ),
    ]
