# Generated by Django 4.1.7 on 2023-05-14 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_alter_sprint_fecha_fin_prevista_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstories',
            old_name='id_proyect',
            new_name='proyect',
        ),
        migrations.AlterField(
            model_name='sprint',
            name='fecha_fin_prevista',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 28, 19, 7, 25, 41910)),
        ),
    ]
