# Generated by Django 4.1.7 on 2023-05-16 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_rename_id_proyect_userstories_proyect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='fecha_fin_prevista',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 20, 16, 41, 506153)),
        ),
    ]
